USE [master]
GO

DROP DATABASE IF EXISTS [LessonPlan]
GO

CREATE DATABASE [LessonPlan]
GO

USE [LessonPlan]
GO

CREATE TABLE [Subject](
	Id INT IDENTITY(1, 1),
	SubjectName NVARCHAR(100) NOT NULL,
	SubjectDescription NVARCHAR(255) NULL,
	CONSTRAINT PK_Subject_Id PRIMARY KEY (Id)
)
CREATE TABLE Teacher(
	Id INT IDENTITY(1, 1),
	TeacherName NVARCHAR(50) NOT NULL,
	TeacherLastname NVARCHAR(50) NOT NULL,
	TeacherPhoneNumber NVARCHAR(9) CHECK(LEN(TeacherPhoneNumber) = 9) NULL,
	CONSTRAINT PK_Teacher_Id PRIMARY KEY (Id)
)
CREATE TABLE Class(
	Id INT IDENTITY(1, 1),
	ClassName NVARCHAR(50) NOT NULL,
	BirthYear DATE NOT NULL,
	CONSTRAINT PK_Class_Id PRIMARY KEY (Id)
)
CREATE TABLE Classroom(
	Id INT IDENTITY(1, 1),
	TeacherId INT NOT NULL,
	ClassId INT NOT NULL,
	ClassroomNumber INT NOT NULL,
	ClassroomQuantity INT NULL,
	CONSTRAINT PK_Classroom_Id PRIMARY KEY (Id)
)

