USE [master]
GO

DROP DATABASE IF EXISTS [LessonPlan]
GO

CREATE DATABASE [LessonPlan]
GO

USE [LessonPlan]
GO

CREATE TABLE Class(
	Id INT IDENTITY(1, 1),
	ClassName NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_Class_Id PRIMARY KEY (Id)
)
CREATE TABLE Subject(
	Id INT IDENTITY(1, 1),
	SubjectName NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_Subject_Id PRIMARY KEY (Id)
)
CREATE TABLE Teacher(
	Id INT IDENTITY(1, 1),
	TeacherName NVARCHAR(50) NOT NULL,
	TeacherLastname NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_Teacher_Id PRIMARY KEY (Id)
)
CREATE TABLE Lesson(
	Id INT IDENTITY(1, 1),
	ClassId INT NOT NULL,
	SubjectId INT NOT NULL,
	TeacherId INT NOT NULL,
	StartLesson TIME NOT NULL,
	EndLesson TIME NOT NULL,
	CONSTRAINT FK_Lesson_ClassId FOREIGN KEY (ClassId) REFERENCES Class (Id),
    CONSTRAINT FK_Lesson_SubjectId FOREIGN KEY (SubjectId) REFERENCES Subject (Id),
    CONSTRAINT FK_Lesson_TeacherId FOREIGN KEY (TeacherId) REFERENCES Teacher (Id) 
)
